//HELLO BOOTCAMPER, FANCY SEEING YOU HERE.
//HOPE YOU CAN HELP ME WITH MY BIRTHDAY PARTY. I FORGOT HOW MANY FRIENDS I HAVE BUT I HAVE
//A LIST WITH SOME NAMES. I NEED TO BUY A BIRTHDAY CAKE BUT NOT SURE HOW MANY PIECES I NEED.
//I REMEMBER NONE OF MY FRIEND'S NAMES HAS NO MORE THAN 5 CHARACTERES
//IF MY LIST IS EMPTY IT SHOULD RETURN 0 FRIENDS
//IF ALL THE NAMES IN THE LIST HAS MORE THAN 4 CHARACTERES IT SHOULD RETURN 0
export function findMyFriends(friends) {}
