//HELLO BOOTCAMPER, FANCY SEEING YOU HERE.
//HOPE YOU CAN HELP ME WITH MY BIRTHDAY PARTY. I FORGOT HOW MANY FRIENDS I HAVE BUT I HAVE
//A LIST WITH SOME NAMES. I NEED TO BUY A BIRTHDAY CAKE BUT NOT SURE HOW MANY PIECES I NEED.
//I REMEMBER NONE OF MY FRIEND'S NAMES IS LONGER THAN 5 CHARACTERES.

export function findMyFriends() {}
